from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPOSITORY_ROOT = SCRIPT_DIR.parents[2]
SERVER_ROOT = REPOSITORY_ROOT / "server"
sys.path.insert(0, str(SERVER_ROOT / "src"))

os.environ.pop("BUZZ_GSC_CREDENTIALS", None)

from server.app import create_app  # noqa: E402
from server.environment import ENVIRONMENT_VARIABLES, EnvironmentVariable  # noqa: E402

OPENAPI_PATH = SCRIPT_DIR.parent / "public" / "openapi.json"
CONFIGURATION_PATH = (
    SCRIPT_DIR.parent / "src" / "content" / "docs" / "reference" / "configuration.md"
)
ENV_EXAMPLE_PATH = SERVER_ROOT / ".env.example"


def display_default(variable: EnvironmentVariable) -> str:
    if variable.default is None:
        return "Not set"
    if variable.name == "BUZZ_DATA_DIR":
        return "Server package directory"
    if isinstance(variable.default, bool):
        return f"`{str(variable.default).lower()}`"
    if isinstance(variable.default, (frozenset, set)) and not variable.default:
        return "Not set"
    return f"`{variable.default}`"


def render_configuration() -> str:
    rows = []
    for variable in ENVIRONMENT_VARIABLES:
        requirement = variable.required or "Optional"
        scope = "Buzz server" if variable.scope == "server" else "Standalone deployment"
        rows.append(
            f"| `{variable.name}` | {variable.description} | {scope} | "
            f"{display_default(variable)} | {requirement} |"
        )

    return """---
title: Configuration
description: Environment variables used by the Buzz server and bundled deployment.
editUrl: false
---

<!-- Generated from server/src/server/environment.py. Do not edit this file. -->

Buzz reads server configuration when the Python modules are imported. Restart the server after changing an environment variable.

Command-line options take precedence where noted. Values used only by the bundled Traefik deployment are marked as standalone deployment settings.

## Environment Variables

| Variable | Purpose | Scope | Default | Requirement |
| --- | --- | --- | --- | --- |
""" + "\n".join(rows) + """

## CLI Environment Variables

The CLI reads `BUZZ_SERVER` and `BUZZ_TOKEN`. The root `--server` and `--token` options take precedence, followed by environment variables, then saved configuration.

Keep secrets outside source control. `GITHUB_CLIENT_SECRET`, `BUZZ_ANALYTICS_SECRET`, `BUZZ_GSC_CREDENTIALS`, `BUZZ_TRAEFIK_CONTROL_TOKEN`, `BUZZ_TRAEFIK_API_AUTHORIZATION`, `CF_API_TOKEN`, and `BUZZ_TOKEN` contain sensitive values.
"""


def render_env_example() -> str:
    by_name = {variable.name: variable for variable in ENVIRONMENT_VARIABLES}

    def setting(name: str, commented: bool = False) -> str:
        variable = by_name[name]
        prefix = "# " if commented else ""
        return f"{prefix}{name}={variable.example or variable.default or ''}"

    return f"""# Buzz server
{setting('BUZZ_DOMAIN')}
{setting('GITHUB_CLIENT_ID')}
{setting('GITHUB_CLIENT_SECRET')}
{setting('BUZZ_DATA_DIR', commented=True)}
{setting('BUZZ_ANALYTICS_SECRET', commented=True)}

# Deployment limits
{setting('BUZZ_MAX_ARCHIVE_BYTES')}
{setting('BUZZ_MAX_SITE_BYTES')}
{setting('BUZZ_MAX_SITE_FILES')}
{setting('BUZZ_MAX_ARCHIVE_PATH_BYTES')}

# Access control
{setting('BUZZ_ALLOW_REGISTRATION', commented=True)}
{setting('BUZZ_ALLOWED_GITHUB_USERS', commented=True)}

# Optional custom domain control plane
{setting('BUZZ_CUSTOM_DOMAINS_ENABLED', commented=True)}
{setting('BUZZ_TRAEFIK_CONTROL_TOKEN', commented=True)}
{setting('BUZZ_TRAEFIK_CONTROL_PORT', commented=True)}
{setting('BUZZ_TRAEFIK_API_URL', commented=True)}
{setting('BUZZ_TRAEFIK_API_AUTHORIZATION', commented=True)}
{setting('BUZZ_TRAEFIK_HTTPS_ENTRYPOINT', commented=True)}
{setting('BUZZ_TRAEFIK_SERVICE', commented=True)}
{setting('BUZZ_CUSTOM_DOMAIN_ROUTING_ENABLED', commented=True)}
{setting('BUZZ_CUSTOM_DOMAIN_ADMISSION_ENABLED', commented=True)}
{setting('BUZZ_CLOUDFLARE_DIAGNOSTICS_ENABLED', commented=True)}
{setting('BUZZ_CLOUDFLARE_ACTIVATION_ENABLED', commented=True)}
{setting('BUZZ_MAX_CUSTOM_DOMAINS_PER_SITE', commented=True)}
{setting('BUZZ_MAX_CUSTOM_DOMAINS_PER_USER', commented=True)}
{setting('BUZZ_MAX_CUSTOM_DOMAINS_SERVER_WIDE', commented=True)}
{setting('BUZZ_CUSTOM_DOMAIN_INGRESS_IPS', commented=True)}
{setting('BUZZ_CUSTOM_DOMAIN_ORIGIN_HOST', commented=True)}
{setting('BUZZ_TRAEFIK_CERT_RESOLVER', commented=True)}
{setting('BUZZ_CUSTOM_DOMAIN_RECONCILE_SECONDS', commented=True)}

# Standalone Docker Compose deployment
{setting('CF_API_TOKEN')}
{setting('ACME_EMAIL')}
{setting('BUZZ_CUSTOM_DOMAIN_ACME_CA_SERVER', commented=True)}

# Google Search Console
{setting('BUZZ_GSC_CREDENTIALS', commented=True)}
{setting('BUZZ_GSC_PROPERTY', commented=True)}
"""


def canonical_openapi() -> str:
    return json.dumps(
        create_app().openapi(),
        sort_keys=True,
        indent=2,
        ensure_ascii=False,
    ) + "\n"


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f"Generated file is stale: {path.relative_to(REPOSITORY_ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Buzz server reference files")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    write_or_check(OPENAPI_PATH, canonical_openapi(), args.check)
    write_or_check(CONFIGURATION_PATH, render_configuration(), args.check)
    write_or_check(ENV_EXAMPLE_PATH, render_env_example(), args.check)


if __name__ == "__main__":
    main()
