import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createProgram } from "../../../cli/src/program.ts";

type BuzzCommand = ReturnType<typeof createProgram>;

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const outputDirectory = join(
  scriptDirectory,
  "../src/content/docs/reference/cli"
);

/** Hidden subcommands (like the default `access status`) and Commander's
 *  implicit `help` are not part of the surface we document. */
function visibleCommands(command: BuzzCommand): BuzzCommand[] {
  return command
    .createHelp()
    .visibleCommands(command)
    .filter((child) => child.name() !== "help") as BuzzCommand[];
}

function configureHelp(command: BuzzCommand): void {
  command.configureOutput({
    getOutHelpWidth: () => 80,
  });
  visibleCommands(command).forEach(configureHelp);
}

function commandPath(command: BuzzCommand): string[] {
  const names: string[] = [];
  let current: BuzzCommand | null = command;
  while (current?.parent) {
    names.unshift(current.name());
    current = current.parent;
  }
  return names;
}

function title(command: BuzzCommand): string {
  return ["buzz", ...commandPath(command)].join(" ");
}

function commandList(command: BuzzCommand): BuzzCommand[] {
  return visibleCommands(command).flatMap((child) => [child, ...commandList(child)]);
}

function commandAnchor(command: BuzzCommand): string {
  return ["buzz", ...commandPath(command)].join("-");
}

function commandIndex(commands: BuzzCommand[]): string {
  return commands
    .map(
      (command) =>
        `- [\`${title(command)}\`](#${commandAnchor(command)}): ${command.description()}`
    )
    .join("\n");
}

function commandSection(command: BuzzCommand): string {
  return `## ${title(command)}

\`\`\`text
${command.helpInformation().trimEnd()}
\`\`\``;
}

function writePage(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content.endsWith("\n") ? content : `${content}\n`);
}

export function generateCliReference(program = createProgram()): void {
  configureHelp(program);
  rmSync(outputDirectory, { recursive: true, force: true });
  mkdirSync(outputDirectory, { recursive: true });

  const commands = commandList(program);

  const overview = `---
title: CLI Reference
description: Commands and options supported by the Buzz CLI.
editUrl: false
---

<!-- Generated from the Commander definitions in cli/src. Do not edit this file. -->

Use this reference to check command syntax and options. Start with [Deploy Your First Site](../../getting-started/deploy-your-first-site/) for a complete workflow.

## Command Index

${commandIndex(commands)}

${[program, ...commands].map(commandSection).join("\n\n")}`;
  writePage(join(outputDirectory, "index.md"), overview);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  generateCliReference();
}
